services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: cosc310-backend
    restart: unless-stopped
    environment:
      - TZ=America/Vancouver
    ports:
      - "8000:8000"
    volumes:
      - platter-data:/app/app/data
    networks:
      - app-net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: cosc310-frontend
    ports:
      - "3000:80"
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      - app-net

networks:
  app-net:
    driver: bridge

volumes:
  platter-data:

